API_ID: 18625698
API_HASH: 9d13ed618423d32c416dbe2f8016fdca
BOT_TOKEN: 5638213042:AAFua97q9GMh1ViV2CxLFQ7V3EEadGxyiqc


MONGO_URL: 
REDIS_URI:
REDIS_PORT:
REDIS_PASS:

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 5362546924

OWNER: 5362546924

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

